# 服务器前置任务(ubuntu使用 Centos项目注释或删掉)
- name: main
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: False
  pre_tasks:
    - name: Install Python
      raw: sudo apt update && sudo apt-get -y install python
      ignore_errors: yes
  
# 核心任务

- name: main
  hosts: all
  become: yes
  become_method: sudo
  vars:
    extra_db_user: db_user
    extra_db: db_name
    extra_db_password: db_pass

  roles:
    - {role: common , tags: "common"}
    - {role: cloud,tags: "cloud"}
    - {role: mariadb,tags: "mariadb",mariadbver: 10.4}
    - { role: end , tags: "end"} 
