- src: http://github.com/websoft9dev/role_common
  version: main

- src: http://github.com/websoft9dev/role_cloud
  version: main

- src: http://github.com/websoft9dev/role_nginx
  version: main

# 根据需求添加相对应的role

- src: http://github.com/websoft9dev/role_preend
  version: main

- src: http://github.com/websoft9dev/role_end
  version: main
